<Project Sdk="Godot.NET.Sdk/4.6.2">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>TacticalBisexualDreams</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Scripts\Gameplay\Player\UnitSelectedStates\AttackSubState.gd" />
    <Content Include="Scripts\Gameplay\Player\UnitSelectedStates\MoveSubState.gd" />
  </ItemGroup>
</Project>